version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:5.0

  nginx:
    container_name: nginx
    image: stringsyncnginx:latest
    volumes:
      - ./nginx/nginx.fakeprod.conf:/etc/nginx/nginx.conf
    links:
      - api
    ports:
      - 80:80

  migrate:
    container_name: migrate
    image: stringsync:latest
    build:
      context: .
    env_file:
      - ./env/fakeprod.env
      - ./env/secrets.env
    links:
      - db
    command: 'bash -c "cd api && yarn migrate && yarn seed"'

  api:
    container_name: api
    image: stringsync:latest
    env_file:
      - ./env/fakeprod.env
      - ./env/secrets.env
    links:
      - db
      - redis
    command: ['node', '/app/api/build/entrypoints/api.js']

  worker:
    container_name: worker
    image: stringsync:latest
    build:
      context: .
    env_file:
      - ./env/fakeprod.env
      - ./env/secrets.env
    environment:
      NODE_ENV: production
      PORT: 3000
    links:
      - db
      - redis
    ports:
      - 3000:3000
    command: ['node', '/app/api/build/entrypoints/worker.js']

  dispatcher:
    container_name: dispatcher
    image: stringsync:latest
    build:
      context: .
    env_file:
      - ./env/fakeprod.env
      - ./env/secrets.env
    environment:
      NODE_ENV: production
      PORT: 3001
    links:
      - db
      - redis
    ports:
      - 3001:3001
    command: ['node', '/app/api/build/entrypoints/dispatcher.js']
