version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - web
    command:
      - "./stringsync"
      - "api"
      - "--port"
      - "8080"
      - "--allowed_origin"
      - "http://localhost:8081"
      - "--allowed_origin"
      - "http://localhost:8080"

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      PORT: 8081
  