version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
    command:
      - "./stringsync"
      - "api"
      - "--port"
      - "8080"
      - "--allowed_origin"
      - "http://localhost:8081"
      - "--allowed_origin"
      - "http://localhost:8080"

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - 5432:5432
  
  migrate:
    build:
      dockerfile: Dockerfile
    links:
      - db
    command:
      - "./stringsync"
      - "migrate"
      - "--host"
      - "db"
      - "--port"
      - "5432"
      - "--dbname"
      - "stringsync"
      - "--user"
      - "stringsync"
      - "--password"
      - "stringsync"
      - "--seed"