version: '3.9'

services:
  test:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: stringsync
      DB_USERNAME: stringsync
      DB_PASSWORD: stringsync
    command:
      - "./stringsync"
      - "test"

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - 5432:5432
