version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - web
      - db
    command:
      - "./stringsync"
      - "api"
      - "--port"
      - "8080"
      - "--allowed_origin"
      - "http://localhost:8081"
      - "--allowed_origin"
      - "http://localhost:8080"

  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - 5432:5432

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      PORT: 8081
  