version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:5.0

  nginx:
    container_name: nginx
    image: nginx:1.21
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    links:
      - api
      - web
    ports:
      - 80:80

  migrate:
    container_name: migrate
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
    command: 'bash -c "yarn migrate && yarn seed"'

  api:
    container_name: api
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
      - redis
    ports:
      - 3000:3000
    command: ['yarn', 'dev:api']

  worker:
    container_name: worker
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    environment:
      PORT: 3001
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
      - redis
    ports:
      - 3001:3001
    command: ['yarn', 'dev:worker']

  dispatch:
    container_name: dispatcher
    image: stringsync:latest
    env_file:
      - env/dev.env
      - env/secrets.env
    environment:
      PORT: 3002
    volumes:
      - ./api/src:/app/api/src
    links:
      - db
      - redis
    ports:
      - 3002:3002
    command: ['yarn', 'dev:dispatcher']

  web:
    container_name: web
    image: stringsync:latest
    volumes:
      - ./web/src:/app/web/src
      - ./web/public:/app/web/public
    command: ['yarn', 'dev:web']
