version: '3.7'

services:
  db:
    container_name: db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: stringsync
      POSTGRES_USER: stringsync
      POSTGRES_PASSWORD: stringsync

  redis:
    container_name: redis
    image: redis:5.0

  nginx:
    container_name: nginx
    image: stringsyncnginx:latest
    volumes:
      - ./nginx/nginx.fakeprod.conf:/etc/nginx/nginx.conf
    links:
      - api
    ports:
      - 80:80

  migrate:
    container_name: migrate
    image: stringsync:latest
    build:
      context: .
    env_file:
      - env/fakeprod.env
      - env/secrets.env
    links:
      - db
    entrypoint: ['./api/bin/wait-for-it.sh', 'db:5432', '--']
    command: 'bash -c "cd api && yarn migrate && yarn seed"'

  api:
    container_name: api
    image: stringsync:latest
    env_file:
      - env/fakeprod.env
      - env/secrets.env
    links:
      - db
      - redis
    command: ['node', '/app/api/build/entrypoints/api.js']

  worker:
    container_name: worker
    image: stringsync:latest
    build:
      context: .
    env_file:
      - env/fakeprod.env
      - env/secrets.env
    environment:
      NODE_ENV: production
    links:
      - db
      - redis
    command: ['node', '/app/api/build/entrypoints/worker.js']
